			<div class="row ">
				
				<div class="col-sm-12 text-center">
				<div class='package brilliant'>
			    <div class='name'><?php if(isset($hovaten)) echo $hovaten; ?></div>
			    <!--
			    <div class='price'>€5</div>
			-->
			    <div class='vip'><?php if(isset($vip)) echo $vip; ?></div>
			    <hr>
			    <ul>
			      <li>
			        <span class="maso"><?php if(isset($maso)) echo $maso; ?></span> <span class="cmtnd"><?php if(isset($cmtnd)) echo $cmtnd; ?> </span>
			      </li>
			      <li>
			        <span class="ngaysinh"><?php if(isset($ngaysinh)) echo $ngaysinh; ?> </span> <span class="gioitinh"><?php if(isset($gioitinh)) echo $gioitinh; ?> </span>
			      </li>
			      <li>
			        <span class="dienthoai"><?php if(isset($dienthoai)) echo $dienthoai; ?></span>   <span class="email"> <?php if(isset($email)) echo $email; ?></span>
			      </li>
			      <li>
			        <span class="diachi"><?php if(isset($diachi)) echo $diachi; ?> </span>
			      </li>
			      <li>
			        <span class="donvi"><?php if(isset($donvi)) echo $donvi; ?></span>
			      </li>
			      <li>
			        <span class="ghichu"> <?php if(isset($ghichu)) echo $ghichu; ?></span>
			      </li>
			    </ul>
			  </div>
				</div>
			</div>
