<!DOCTYPE html>
<html lang="vi">
<head>

<?php include './views/ndhheader.phtml'; ?> 
<link href="./css/radio.css" rel="stylesheet" type="text/css" />
<link href="./css/text1.css" rel="stylesheet" type="text/css" />
<link href="./css/infovip.css" rel="stylesheet" type="text/css" />
<script type="text/javascript" src="./js/khachhang5.js"></script>
</head>
<body>
	<?php echo thanhTieuDe($tieudechinh,$arr); ?>
	<br>
	<div class="container">
		<?php 
			if(isset($status)) echo $status;
			
		?>
		
		<br><br>
		<form action="./index.php" method="POST">
			<input type=hidden name=ylan value="khachhang5"> 
			<input type=hidden name=token value="<?php echo $token; ?>">
			<div class="row dong">
				<div class="col-sm-12 text-center">
					
					<span class="text-center"> 
						<button type="button" class="btn btn-primary" onclick='window.location="index.php?ylan=khachhang5&type=1"' > <i class="fa fa-step-backward" aria-hidden="true"></i>
						</button>
						&nbsp;
						<button type="button" class="btn btn-primary" onclick='window.location="index.php?ylan=khachhang5&type=2&ms=<?php if(isset($maso)) echo $maso; ?>"' > <i class="fa fa-backward" aria-hidden="true"></i>
						</button>
						<input type="number" name="maso" id="maso" class="txt" value="<?php if(isset($maso)) echo $maso; ?>">
						<button type="submit" name="submit" class="btn btn-primary" > <i class="fa fa-search" aria-hidden="true"></i></button>
						<button type="button" class="btn btn-primary" onclick='window.location="index.php?ylan=khachhang5&type=3&ms=<?php if(isset($maso)) echo $maso; ?>"' > <i class="fa fa-forward" aria-hidden="true"></i>
						</button>&nbsp;
						<button type="button" class="btn btn-primary" onclick='window.location="index.php?ylan=khachhang5&type=4"' > <i class="fa fa-step-forward" aria-hidden="true"></i>
						</button>
					</span>
				</div>
			</div>
			<br>
			<?php 
			if(isset($error)) echo $error;
			else {
				include './views/khachhang51.phtml';
			}
			
			?>
			
		</form>
		<br><br>
	</div>
</body>
</html>
