<!DOCTYPE html>
<html lang="vi">
<head>

<?php include './views/ndhheader.phtml'; ?> 
<link href="./css/text1.css" rel="stylesheet" type="text/css" />
<link href="./css/table5.css" rel="stylesheet" type="text/css" />



<script >
	$(document).ready(function() {
		//$("#fixTable").tableHeadFixer({"head" : false, "left" : 3}); 
		$("#month").on("change",function(){
      var id=$("#month").val();
      $.get("index.php",{ylan:"lichtrucmod2",month:"'"+id+"'"},function(data){
	        $("#ketQua").html(data);
	      //  $("#fixTable").tableHeadFixer({"head" : false, "left" : 3});
	      });
      
  });
	});
</script>
</head>
<body>
<?php echo thanhTieuDe($tieudechinh,$arr); ?>
<br>
<div class="container">
<br>
<?php 
	if(isset($error)) echo $error;
	if(isset($status)) echo $status;
?>
<br>
	<div class="row">
		<div class="col-sm-3 text-left"><?php echo $quyen ?> </div>
		<div class="col-sm-6">
			Chọn tháng cần xem
			<input type="month" name="month" id="month" class="txt" <?php if(isset($dtime)) echo 'value="'.$dtime.'"';?> >
		</div>
	</div>
<br><div class="row">
	<div class="col-sm-1"> </div>
		<div class="col-sm-6 text-left">
			
		</div>	
</div>

	<div class="row ">
		
		<div class="col-sm-12">
			<div id="ketQua">
				<?php if(isset($lich)) echo $lich;?>
			</div>
		</div>
	</div>
    
</div>


</body>
</html>
