<!DOCTYPE html>
<html lang="vi">
<head>

<?php include './views/ndhheader.phtml'; ?> 
<link href="./css/login.css" rel="stylesheet" type="text/css" />
</head>
<body>

<div class="container">
<div class="row">
	<div class="col-sm-12">	
		<?php if(isset($error)) echo "<br><div class='alert alert-danger text-center'>".$error."</div>"; ?>
		<?php if(isset($success)) echo "<br><div class='alert alert-success text-center'>".$success."</div>" ; ?>
	</div>
</div>
&nbsp;<br>
<div class="row">
	<div class="col-sm-12 text-center">	 
		<img src="./images/logomthl.png" width="310" height="207" align="text-center">
	</div>
</div>

<form action="./login2" method="POST" >
	<!--<input type=hidden name=ylan value="login">  -->
	<input type=hidden name=token value="<?php echo $token; ?>">
	<?php 
		if(isset($phonglam)) echo '<input type=hidden name=phonglam value="'.$phonglam.'"> '; 
	?> 
	<div class="clearfix"> </div>
	<div class="form-3">
		<div class="row">
			<div class="col-sm-8 col-lg-5">
				<label>	User name </label>
			</div>
			<div class="col-sm-6 col-lg-7">
				<input type="text" name="username" id="login" placeholder="Nhập...">
			</div>
		</div>
		
		<div class="row">
			<div class="col-sm-8 col-lg-5">
				<label> Passwords </label>
			</div>
			<div class="col-sm-6 col-lg-7">
				<input type="password" name="password" id="password" >
			</div>
		</div>
		<div class="row">
			<div class="col-sm-12 text-center">
				&nbsp;<br>
				<input type="submit" name="submit" value="ĐĂNG NHẬP">
			</div>
		</div>
		   
	</div>
</form>
</div>
</div>
</body>
</html>