<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1">
<link href="./images/favicon.ico" rel="shortcut icon" />
<link href="./css/font-awesome.css" rel="stylesheet" type="text/css"/>
<link href="./css/form.css" rel="stylesheet" type="text/css" />
<link href="./css/header.css" rel="stylesheet" type="text/css" />
<link href="./css/bootstrap.css" rel="stylesheet" type="text/css" />
<script type="text/javascript" src="./js/jquery-3.2.1.js"></script>
<script type="text/javascript" src="./js/bootstrap.js"></script>

<title><?php echo $chuongtrinh ?></title>