<!DOCTYPE html>
<html lang="vi">
<head>
<?php include './views/ndhheader.phtml'; ?> 
<link href="./css/text1.css" rel="stylesheet" type="text/css" />

</head>
<body>
<?php echo thanhTieuDe($tieudechinh,$arr); ?>

<div class="container">
  <?php 
    if(isset($error)) echo $error;
    if(isset($status)) echo $status;

  ?>
	<br>
<br><br>
  <form action="./index.php" method="POST">
  <input type=hidden name=ylan value="nhanemailni"> 
  <input type=hidden name=token value="<?php echo $token; ?>">
  <?php if(isset($list)) echo $list; ?>
  
  
</form>

</div>


</body>
</html>


