<br>

<div class="row">
     <div class="col-sm-1 "> </div>
     <div class="col-sm-4 ">
          <button type="button" class="btn btn-success btn-block btn-lg"  data-toggle="collapse" data-target="#hethong" > &nbsp;Hệ thống </button>
          <div id="hethong" class="collapse"> <br>
               <button type="button" class="btn btn-warning btn-block btn-lg" onclick='window.location="./nhatky"'> Xem nhật ký hệ thống </button>
               <button type="button" class="btn btn-warning btn-block btn-lg" onclick='window.location="./data"'> Xem cấu trúc CSDL </button>

          </div>
          
     </div>
     <div class="col-sm-1 "> </div>
     <div class="col-sm-4 ">
          <button type="button" class="btn btn-success btn-block btn-lg"  data-toggle="collapse" data-target="#quanly" > &nbsp;Quản lý </button>
          <div id="quanly" class="collapse"> <br>
               <button type="button" class="btn btn-warning btn-block btn-lg" onclick='window.location="./user_ql"'> Quản lý user </button>
               <button type="button" class="btn btn-warning btn-block btn-lg" onclick='window.location="./donvi"'> Quản lý đơn vị </button>
               <button type="button" class="btn btn-warning btn-block btn-lg" onclick='window.location="./vip_ranks"' > &nbsp;Quản lý loại VIP</button>
               
               <button type="button" class="btn btn-warning btn-block btn-lg" onclick='window.location="./noidungmau"'> Nội dung mẫu khảo sát </button>
          </div>
          
     </div>
</div>
<br>
<div class="row">
     <div class="col-sm-1 "> </div>
     <div class="col-sm-4 ">
          <button type="button" class="btn btn-success btn-block btn-lg"  data-toggle="collapse" data-target="#quanlymod" > &nbsp;Quản lý MOD </button>
          <div id="quanlymod" class="collapse"> <br>
               <button type="button" class="btn btn-secondary btn-block btn-lg" onclick='window.location="./trucmod"' > &nbsp;Danh sách người trực MOD </button>
               <button type="button" class="btn btn-secondary btn-block btn-lg" onclick='window.location="./nhanemailni"' > &nbsp;DS người nhận email NI trực MOD </button>
               <button type="button" class="btn btn-secondary btn-block btn-lg" onclick='window.location="./catrucmod"' > &nbsp;Quản lý tên ca trực MOD </button>
          </div>
     </div>
     <div class="col-sm-1 "> </div>
     <div class="col-sm-4 ">
          
     </div>
</div>
<br>
<div class="row">
     <div class="col-sm-1 "> </div>
     <div class="col-sm-4 ">
          
     </div>
     <div class="col-sm-1 "> </div>
     <div class="col-sm-4 ">
          
     </div>
</div>
