<!DOCTYPE html>
<html lang="vi">
<head>

<?php include './views/ndhheader.phtml'; ?> 
<link href="./css/radio.css" rel="stylesheet" type="text/css" />
<link href="./css/text1.css" rel="stylesheet" type="text/css" />
<script type="text/javascript" src="./js/xemphieu.js"></script>
</head>
<body>
	<?php echo $showheader;?>
	<br>
	<div class="container">
	<h1 class="tieudechinh"> <?php echo $tieudechinh;?></h1>
	<br><br>
	<?php if(isset($noidungphieu)) echo $noidungphieu;?>
</div>
</body>
</html>
<textarea name="" id="" cols="30" rows="10"></textarea>