<div class="row dong">
		<div class="col-sm-3"> </div>
		<div class="col-sm-6">
			<span class="text-left">Họ và tên:</span><br>
			<span class="text-center"> <input type="text" class="txt" name="name" id="name" value="<?php if(isset($fullname)) echo $fullname; else echo ''; ?>" required> </span>
		</div>
	</div>
	<div class="row dong">
		<div class="col-sm-3"> </div>
		<div class="col-sm-6">
			<span class="text-left"><input type="checkbox"  <?php if(isset($checkadmin))echo $checkadmin; ?> name="admin"> Là người quản trị(Admin)</span><br>
			<span class="text-center">  </span>
		</div>
	</div>
	<div class="row dong">
		<div class="col-sm-3"> </div>
		<div class="col-sm-6">
			<span class="text-left"><input type="checkbox" <?php if(isset($checkadmin2))echo $checkadmin2; ?> name="admin2"  > Là người quản lý:</span><br>
			<span class="text-center">  </span>
		</div>
	</div>
	<div class="row dong">
		<div class="col-sm-3"> </div>
		<div class="col-sm-6">
			<span class="text-left">Thuộc đơn vị:</span><br>
				<?php echo loadDanhSachDonVi($donvi); ?>
		</div>
	</div>