<!DOCTYPE html>
<html lang="vi">
<head>

<?php include './views/ndhheader.phtml'; ?> 

</head>
<body>
	<?php echo $showheader;?>
<br>
<div class="container">
	<?php 
		if(isset($error)) echo $error;
		if(isset($status)) echo $status;

	?>

	<h1 class="tieudechinh"> <?php echo $tieudechinh;?></h1>
	<br><br>
	<form action="./index.php" method="POST">
	<input type=hidden name=ylan value="user_up"> 
	<input type=hidden name=token value="<?php echo $token; ?>">	
	
	<div class="row">
		<div class="col-sm-5"> </div>
		<div class="col-sm-6">
			<span class="text-left">Tên đăng nhập:<strong><?php echo $user; ?> </strong> </span><br>
			
		</div>
	</div>
	<div class="row dong">
		<div class="col-sm-5"> </div>
		<div class="col-sm-6">
			<span class="text-left">Họ và tên:</span><br>
			<span class="text-center"> <input type="text" name="name" value=" <?php echo $name; ?>"> </span>
		</div>
	</div>
		<div class="row dong">
		<div class="col-sm-5"> </div>
		<div class="col-sm-6">
			<span class="text-left">Mật khẩu hiện tại:</span><br>
			<span class="text-center"> <input type="password" name="oldpass"> </span>
		</div>
	</div>
	
		<div class="row dong">
		<div class="col-sm-5"> </div>
		<div class="col-sm-6">
			<span class="text-left">Mật khẩu mới:</span><br>
			<span class="text-center"> <input type="password" name="newpass"> </span>
		</div>
	</div>

		<div class="row dong">
		<div class="col-sm-5"> </div>
		<div class="col-sm-6">
			<span class="text-left">Xác nhận mật khẩu mới:</span><br>
			<span class="text-center"> <input type="password" name="renewpass"> </span>
		</div>
	</div>
	
	

		
	<div class="row">
		
		<div class="col-sm-12 text-center">
			<input type="submit" class="submitbutton" name="submit" value="<?php echo $tieudesubmit;?>">  
		</div>
	</div>
	</form>
</body>
</html>