<!DOCTYPE html>
<html lang="vi">
<head>

<?php include './views/ndhheader.phtml'; ?> 
<script type="text/javascript" src="./js/user.js"></script>
</head>
<body>
	<?php echo thanhTieuDe($tieudechinh,$arr); ?>
<br>
<div class="container">
	<?php 
		if(isset($error)) echo $error;
		if(isset($status)) echo $status;

	?>

	<br><br>
	<form action="./index.php" method="POST">
	<input type=hidden name=ylan value="user"> 
	<input type=hidden name=token value="<?php echo $token; ?>">	
	
	<div class="row <?php if(isset($dongdangnhap)) echo $dongdangnhap; ?>">
		<div class="col-sm-3"> </div>
		<div class="col-sm-6">
			<span class="text-left">Tên đăng nhập:</span><br>
			<span class="text-center"> <input type="text" class="txt" name="user" id="user" <?php echo $tendangnhap; ?>   > </span>
			<span id=ketQua></span>
		</div>
	</div>
	<?php if(isset($showpass)) include './views/user_pass.phtml';  ?>
	<?php if(isset($usercreate)) include './views/user_create.phtml';  ?>
	<div class="row">
		
		<div class="col-sm-8 text-center">
			<input type="submit" class="submitbutton" name="submit" value="<?php echo $tieudesubmit;?>">  
		</div>
	</div>
	</form>
</body>
</html>