<div class="row dong">
		<div class="col-sm-3"> </div>
		<div class="col-sm-6">
			<span class="text-left">Mật khẩu:</span><br>
			<span class="text-center"> <input type="password" name="pass" class="txt"> </span>
		</div>
	</div>
	<div class="row dong">
		<div class="col-sm-3"> </div>
		<div class="col-sm-6">
			<span class="text-left">Xác nhận mật khẩu:</span><br>
			<span class="text-center"> <input type="password" name="repass" class="txt"> </span>
		</div>
	</div>