<!DOCTYPE html>
<html lang="vi">
<head>

<?php include './views/ndhheader.phtml'; ?> 
<link href="./css/radio.css" rel="stylesheet" type="text/css" />
<link href="./css/text1.css" rel="stylesheet" type="text/css" />
<script type="text/javascript" src="./js/xemphieu.js"></script>
</head>
<body>
	<?php echo $showheader;?>
	<br>
	<div class="container">
	<?php 
		if(isset($error)) echo $error;
		if(isset($status)) echo $status;

	?>
	<h1 class="tieudechinh"> <?php echo $tieudechinh;?></h1>
	<br><br>
	<form action="./index.php" method="POST">
	<input type=hidden name=ylan value="xemphieu"> 
	<?php echo $donvi;?>
	<input type=hidden name=token value="<?php echo $token; ?>">
	<div class="row dong">
		<div class="col-sm-3"> </div>
		<div class="col-sm-6">
			<span class="text-left">Chọn tháng để xem</span><br>
			<span class="text-center"> 
				<input type="month" name="month" id="month" class="txt">
			</span>
		</div>
	</div>
	
	<div class="row">
        <div class="col-sm-2"></div>
        <div class="col-sm-6 ">
            <span id=ketQua></span>
        </div>
    </div>

</form>
</div>
</body>
</html>