<?php
$grcl=array();
$i=0;
$grcl[$i]['noidung']='Kiểm tra bởi';
$grcl[$i]['bien']='nguoi_kiem_tra';
$grcl[$i]['type']='1';
$i++;
$grcl[$i]['noidung']='Ngày';
$grcl[$i]['bien1']='ngay_kiem_tra';
$grcl[$i]['type']='2';
$grcl[$i]['bien2']='ca_truc';

$i++;
$grcl[$i]['noidung']='Khu vực kiểm tra';
$grcl[$i]['bien1']='phong1';
$grcl[$i]['bien2']='phong2';
$grcl[$i]['type']='3';
$i++;
$grcl[$i]['noidung']='Cửa trước';
$grcl[$i]['type']='4';
$i++;
$grcl[$i]['noidung']='Chuông cửa & mắt thần ';
$grcl[$i]['bien']='fd_chuong_cua';
$grcl[$i]['type']='5';
$i++;
$grcl[$i]['noidung']='Sơ đồ thoát hiểm ';
$grcl[$i]['bien']='fd_so_do';
$grcl[$i]['type']='5';
$i++;
$grcl[$i]['noidung']='Chốt cửa an toàn';
$grcl[$i]['bien']='fd_chot_cua';
$grcl[$i]['type']='5';
$i++;
$grcl[$i]['noidung']='Đèn không làm phiền/Làm phòng ';
$grcl[$i]['bien']='fd_khong_lam_phien';
$grcl[$i]['type']='5';
$i++;
$grcl[$i]['noidung']='Cửa & khuôn cửa ';
$grcl[$i]['bien']='fd_khuon_cua';
$grcl[$i]['type']='5';
$i++;
$grcl[$i]['noidung']='Khu vực ra vào';
$grcl[$i]['type']='4';
$i++;
$grcl[$i]['noidung']='Đèn trần ';
$grcl[$i]['bien']='en_den_tran';
$grcl[$i]['type']='5';
$i++;
$grcl[$i]['noidung']='Mùi phòng ';
$grcl[$i]['bien']='en_mui_phong';
$grcl[$i]['type']='5';
$i++;
$grcl[$i]['noidung']='Độ sạch gương ';
$grcl[$i]['bien']='en_do_sach_guong';
$grcl[$i]['type']='5';
$i++;
$grcl[$i]['noidung']='Máy pha trà và Cà phê ';
$grcl[$i]['bien']='en_may_pha_tra';
$grcl[$i]['type']='5';
$i++;
$grcl[$i]['noidung']='Tủ quần áo ';
$grcl[$i]['bien']='en_tu_quan_ao';
$grcl[$i]['type']='5';
$i++;
$grcl[$i]['noidung']='Tiêu chuẩn đồ dùng ';
$grcl[$i]['bien']='en_tieu_chuan_do_dung';
$grcl[$i]['type']='5';
$i++;
$grcl[$i]['noidung']='Két an toàn ';
$grcl[$i]['bien']='en_ket_an_toan';
$grcl[$i]['type']='5';
$i++;
$grcl[$i]['noidung']='Tủ đồ uống ';
$grcl[$i]['type']='4';
$i++;
$grcl[$i]['noidung']='Vị trí bảng giá mini bar ';
$grcl[$i]['bien']='minibar_vi_tri';
$grcl[$i]['type']='5';
$i++;
$grcl[$i]['noidung']='Đồ minibar đúng vị trí & cập nhật ';
$grcl[$i]['bien']='minibar_cap_nhat';
$grcl[$i]['type']='5';
$i++;
$grcl[$i]['noidung']='Hạn sử dụng đồ uống ';
$grcl[$i]['bien']='minibar_exp';
$grcl[$i]['type']='5';
$i++;
$grcl[$i]['noidung']='Điều hòa ';
$grcl[$i]['type']='4';
$i++;
$grcl[$i]['noidung']='Bảng điều khiển ';
$grcl[$i]['bien']='air_dieu_khien';
$grcl[$i]['type']='5';
$i++;
$grcl[$i]['noidung']='Cài đặt tiêu chuẩn và chống ồn ';
$grcl[$i]['bien']='air_tieu_chuan';
$grcl[$i]['type']='5';
$i++;
$grcl[$i]['noidung']='Độ sạch cửa điều hòa ';
$grcl[$i]['bien']='air_do_sach';
$grcl[$i]['type']='5';
$i++;
$grcl[$i]['noidung']='Tivi ';
$grcl[$i]['type']='4';
$i++;
$grcl[$i]['noidung']='Sạch ';
$grcl[$i]['bien']='tv_sach';
$grcl[$i]['type']='5';
$i++;
$grcl[$i]['noidung']='Điều khiển ';
$grcl[$i]['bien']='tv_dieu_khien';
$grcl[$i]['type']='5';
$i++;
$grcl[$i]['noidung']='Vị trí bảng kênh ';
$grcl[$i]['bien']='tv_kenh';
$grcl[$i]['type']='5';
$i++;
$grcl[$i]['noidung']='Độ chính xác bảng kênh ';
$grcl[$i]['bien']='tv_kenh2';
$grcl[$i]['type']='5';
$i++;
$grcl[$i]['noidung']='Chất lượng các kênh ';
$grcl[$i]['bien']='tv_chat_luong';
$grcl[$i]['type']='5';
$i++;
$grcl[$i]['noidung']='Tủ đầu giường ';
$grcl[$i]['type']='4';
$i++;
$grcl[$i]['noidung']='Bộ điều khiển đèn trung tâm ';
$grcl[$i]['bien']='tu_dieu_khien';
$grcl[$i]['type']='5';
$i++;
$grcl[$i]['noidung']='Chụp đèn ';
$grcl[$i]['bien']='tu_chup_den';
$grcl[$i]['type']='5';
$i++;
$grcl[$i]['noidung']='Đồng hồ báo thức ';
$grcl[$i]['bien']='tu_dong_ho';
$grcl[$i]['type']='5';
$i++;
$grcl[$i]['noidung']='Điện thoại bàn ';
$grcl[$i]['bien']='tu_dien_thoai';
$grcl[$i]['type']='5';
$i++;
$grcl[$i]['noidung']='Bàn làm việc ';
$grcl[$i]['type']='4';
$i++;
$grcl[$i]['noidung']='Điện thoại bàn ';
$grcl[$i]['bien']='blv_dien_thoai';
$grcl[$i]['type']='5';
$i++;
$grcl[$i]['noidung']='Cuốn sách chỉ dẫn dịch vụ ';
$grcl[$i]['bien']='blv_sach';
$grcl[$i]['type']='5';
$i++;
$grcl[$i]['noidung']='Bộ phong bì/ giấy/ bút ';
$grcl[$i]['bien']='blv_giay_but';
$grcl[$i]['type']='5';
$i++;
$grcl[$i]['noidung']='Đèn bàn ';
$grcl[$i]['bien']='blv_den_ban';
$grcl[$i]['type']='5';
$i++;
$grcl[$i]['noidung']='Sọt rác ';
$grcl[$i]['bien']='blv_sot_rac';
$grcl[$i]['type']='5';
$i++;
$grcl[$i]['noidung']='Giường ngủ ';
$grcl[$i]['type']='4';
$i++;
$grcl[$i]['noidung']='Ga giường là phẳng ';
$grcl[$i]['bien']='Bed_ga';
$grcl[$i]['type']='5';
$i++;
$grcl[$i]['noidung']='Đầu giường ';
$grcl[$i]['bien']='bed_head';
$grcl[$i]['type']='5';
$i++;
$grcl[$i]['noidung']='Phòng khách ';
$grcl[$i]['type']='4';
$i++;
$grcl[$i]['noidung']='Ghế sofa & bàn uống nước ';
$grcl[$i]['bien']='pk_sofa';
$grcl[$i]['type']='5';
$i++;
$grcl[$i]['noidung']='Giá hành lý ';
$grcl[$i]['bien']='pk_hanh_ly';
$grcl[$i]['type']='5';
$i++;
$grcl[$i]['noidung']='Thảm/ sàn ';
$grcl[$i]['bien']='pk_tham';
$grcl[$i]['type']='5';
$i++;
$grcl[$i]['noidung']='Giấy dán tường ';
$grcl[$i]['bien']='pk_giay_dan_tuong';
$grcl[$i]['type']='5';
$i++;
$grcl[$i]['noidung']='Rèm đêm & rèm ngày ';
$grcl[$i]['bien']='pk_rem';
$grcl[$i]['type']='5';
$i++;
$grcl[$i]['noidung']='Cửa kính và khung kính ';
$grcl[$i]['bien']='pk_kinh';
$grcl[$i]['type']='5';
$i++;
$grcl[$i]['noidung']='Phòng tắm ';
$grcl[$i]['type']='4';
$i++;
$grcl[$i]['noidung']='Sàn và mạch sàn ';
$grcl[$i]['bien']='br_san';
$grcl[$i]['type']='5';
$i++;
$grcl[$i]['noidung']='Mặt bàn rửa mặt ';
$grcl[$i]['bien']='br_ban_rua';
$grcl[$i]['type']='5';
$i++;
$grcl[$i]['noidung']='Thoát nước bồn rửa ';
$grcl[$i]['bien']='br_thoat_bon';
$grcl[$i]['type']='5';
$i++;
$grcl[$i]['noidung']='Áp lực nước ';
$grcl[$i]['bien']='br_ap_luc_nuoc';
$grcl[$i]['type']='5';
$i++;
$grcl[$i]['noidung']='Đèn ';
$grcl[$i]['bien']='br_den';
$grcl[$i]['type']='5';
$i++;
$grcl[$i]['noidung']='Bộ vòi tắm ';
$grcl[$i]['bien']='br_voi_tam';
$grcl[$i]['type']='5';
$i++;
$grcl[$i]['noidung']='Đá trang trí ';
$grcl[$i]['bien']='br_da';
$grcl[$i]['type']='5';
$i++;
$grcl[$i]['noidung']='Hộp giấy ăn ';
$grcl[$i]['bien']='br_giay_an';
$grcl[$i]['type']='5';
$i++;
$grcl[$i]['noidung']='Kính phòng tắm ';
$grcl[$i]['bien']='br_kinh_tam';
$grcl[$i]['type']='5';
$i++;
$grcl[$i]['noidung']='Khăn mặt ';
$grcl[$i]['bien']='br_khan_mat';
$grcl[$i]['type']='5';
$i++;
$grcl[$i]['noidung']='Đĩa đựng và xà phòng ';
$grcl[$i]['bien']='br_xa_phong';
$grcl[$i]['type']='5';
$i++;
$grcl[$i]['noidung']='Khăn tắm ';
$grcl[$i]['bien']='br_khan_tam';
$grcl[$i]['type']='5';
$i++;
$grcl[$i]['noidung']='Bồn tắn đứng ';
$grcl[$i]['bien']='br_bon_tam_dung';
$grcl[$i]['type']='5';
$i++;
$grcl[$i]['noidung']='Điện thoại ';
$grcl[$i]['bien']='br_dien_thoai';
$grcl[$i]['type']='5';
$i++;
$grcl[$i]['noidung']='Thùng rác ';
$grcl[$i]['bien']='br_thung_rac';
$grcl[$i]['type']='5';
$i++;
$grcl[$i]['noidung']='Lọ hoa & hoa ';
$grcl[$i]['bien']='br_hoa';
$grcl[$i]['type']='5';
$i++;
$grcl[$i]['noidung']='Cân sức khỏe ';
$grcl[$i]['bien']='br_can_suc_khoe';
$grcl[$i]['type']='5';
$i++;
$grcl[$i]['noidung']='Áo tắm ';
$grcl[$i]['bien']='br_ao_tam';
$grcl[$i]['type']='5';
$i++;
$grcl[$i]['noidung']='Bồn vệ sinh toilet ';
$grcl[$i]['bien']='br_toilet';
$grcl[$i]['type']='5';
$i++;
$grcl[$i]['noidung']='Giật nước ';
$grcl[$i]['bien']='br_giat_nuoc';
$grcl[$i]['type']='5';
$i++;
$grcl[$i]['noidung']='Giấy dán tường ';
$grcl[$i]['bien']='br_giay_dan_tuong';
$grcl[$i]['type']='5';
$i++;
$grcl[$i]['noidung']='Mục khác ';
$grcl[$i]['type']='4';
$i++;
$grcl[$i]['noidung']='Tranh ảnh/ deco ';
$grcl[$i]['bien']='khac_deco';
$grcl[$i]['type']='5';
$i++;
$grcl[$i]['noidung']='Hành lang ';
$grcl[$i]['bien']='khac_hanh_lang';
$grcl[$i]['type']='5';
$i++;
$grcl[$i]['noidung']='Đánh giá khác( Nếu có) ';
$grcl[$i]['bien']='khac';
$grcl[$i]['type']='6';
$i++;
$grcl[$i]['noidung']='Quản lý ca trực ';
$grcl[$i]['type']='4';
$i++;
$grcl[$i]['noidung']='Tên: ';
$grcl[$i]['bien']='mod_ten';
$grcl[$i]['type']='8';
$i++;
$grcl[$i]['noidung']='Ngày: ';
$grcl[$i]['bien']='mod_ngay';
$grcl[$i]['type']='9';

for ($i=0; $i < count($grcl); $i++) { 
	switch ($grcl[$i]['type']) {
		case '1':
		case '6':
		case '8':
		case '9':
			$grcl[$i]['sql']='grcl_'.$grcl[$i]['bien'];
			break;
		case '2':
		case '3':
			$grcl[$i]['sql1']='grcl_'.$grcl[$i]['bien1'];
			$grcl[$i]['sql2']='grcl_'.$grcl[$i]['bien2'];
			break;
		case '5':
			$grcl[$i]['bien1']=$grcl[$i]['bien'].'_1';
			$grcl[$i]['bien2']=$grcl[$i]['bien'].'_2';
			$grcl[$i]['bien_txt_1']=$grcl[$i]['bien'].'_txt_1';
			$grcl[$i]['bien_txt_2']=$grcl[$i]['bien'].'_txt_2';
			$grcl[$i]['sql1']='grcl_'.$grcl[$i]['bien1'];
			$grcl[$i]['sql2']='grcl_'.$grcl[$i]['bien2'];
			$grcl[$i]['sql_txt_1']='grcl_'.$grcl[$i]['bien_txt_1'];
			$grcl[$i]['sql_txt_2']='grcl_'.$grcl[$i]['bien_txt_2'];
			break;
	}
}

?>