<?php
// Manager  On Duty Checklist
$mod_c=array();
$i=0;
$mod_c[$i]['noidung']='Họ tên người trực';
$mod_c[$i]['bien']='ho_ten';
$mod_c[$i]['sql']='modc_ho_ten';
$mod_c[$i]['type']=3;
$i++;//1
$mod_c[$i]['noidung']='Ngày trực';
$mod_c[$i]['bien']='ngay_truc';
$mod_c[$i]['sql']='modc_ngay_truc';
$mod_c[$i]['bien2']='ca_truc';
$mod_c[$i]['sql2']='modc_ca_truc';
$mod_c[$i]['type']=4;
$i++;//2
$mod_c[$i]['noidung']='Phía ngoài khách sạn';
$mod_c[$i]['bien']='phia_ngoai';
$mod_c[$i]['sql']='modc_phia_ngoai';
$mod_c[$i]['type']=1;
$i++;
$mod_c[$i]['noidung']='Mặt tiền khách sạn';
$mod_c[$i]['bien']='mat_tien';
$mod_c[$i]['sql']='modc_mat_tien';
$mod_c[$i]['type']=0;
$i++;
$mod_c[$i]['noidung']='Biển báo, Logo Mường Thanh';
$mod_c[$i]['bien']='bien_bao';
$mod_c[$i]['sql']='modc_bien_bao';
$mod_c[$i]['type']=0;
$i++;
$mod_c[$i]['noidung']='Đèn bật theo thời gian biểu';
$mod_c[$i]['bien']='phia_ngoai_den_bat';
$mod_c[$i]['sql']='modc_phia_ngoai_den_bat';
$mod_c[$i]['type']=0;
$i++;
$mod_c[$i]['noidung']='Hoa và Cây xanh';
$mod_c[$i]['bien']='hoa_cay_xanh';
$mod_c[$i]['sql']='modc_hoa_cay_xanh';
$mod_c[$i]['type']=0;
$i++;
$mod_c[$i]['noidung']='Cột cờ và cờ';
$mod_c[$i]['bien']='cot_co';
$mod_c[$i]['sql']='modc_cot_co';
$mod_c[$i]['type']=0;
$i++;
$mod_c[$i]['noidung']='Tình trạng vệ sinh';
$mod_c[$i]['bien']='ve_sinh_ben_ngoai';
$mod_c[$i]['sql']='modc_ve_sinh_ben_ngoai';
$mod_c[$i]['type']=0;
$i++;
$mod_c[$i]['noidung']='Tháp nước bật theo thời gian biểu';
$mod_c[$i]['bien']='thap_nuoc';
$mod_c[$i]['sql']='modc_thap_nuoc';
$mod_c[$i]['type']=0;
$i++;
$mod_c[$i]['noidung']='Khu vực phía sau';
$mod_c[$i]['bien']='phia_sau';
$mod_c[$i]['sql']='modc_phia_sau';
$mod_c[$i]['type']=1;
$i++;
$mod_c[$i]['noidung']='Nhà rác';
$mod_c[$i]['bien']='nha_rac';
$mod_c[$i]['sql']='modc_nha_rac';
$mod_c[$i]['type']=0;
$i++;
$mod_c[$i]['noidung']='Khu vực nhận hàng';
$mod_c[$i]['bien']='nhan_hang';
$mod_c[$i]['sql']='modc_nhan_hang';
$mod_c[$i]['type']=0;
$i++;
$mod_c[$i]['noidung']='Khu vực thay đồ của nhân viên';
$mod_c[$i]['bien']='thay_do';
$mod_c[$i]['sql']='modc_thay_do';
$mod_c[$i]['type']=0;
$i++;
$mod_c[$i]['noidung']='Nhà ăn nhân viên';
$mod_c[$i]['bien']='nha_an';
$mod_c[$i]['sql']='modc_nha_an';
$mod_c[$i]['type']=0;
$i++;
$mod_c[$i]['noidung']='Bếp nhân viên';
$mod_c[$i]['bien']='bep_nhan_vien';
$mod_c[$i]['sql']='modc_bep_nhan_vien';
$mod_c[$i]['type']=0;
$i++;
$mod_c[$i]['noidung']='Cổng ra vào dành cho nhân viên';
$mod_c[$i]['bien']='cong_nhan_vien';
$mod_c[$i]['sql']='modc_cong_nhan_vien';
$mod_c[$i]['type']=0;
$i++;
$mod_c[$i]['noidung']='Khu vực Sơ chế';
$mod_c[$i]['bien']='so_che';
$mod_c[$i]['sql']='modc_so_che';
$mod_c[$i]['type']=0;
$i++;
$mod_c[$i]['noidung']='Khu vực bếp chính';
$mod_c[$i]['bien']='bep_chinh';
$mod_c[$i]['sql']='modc_bep_chinh';
$mod_c[$i]['type']=0;
$i++;
$mod_c[$i]['noidung']='Khu vực bếp lạnh';
$mod_c[$i]['bien']='bep_lanh';
$mod_c[$i]['sql']='modc_bep_lanh';
$mod_c[$i]['type']=0;
$i++;
$mod_c[$i]['noidung']='Bếp Bánh';
$mod_c[$i]['bien']='bep_banh';
$mod_c[$i]['sql']='modc_bep_banh';
$mod_c[$i]['type']=0;
$i++;
$mod_c[$i]['noidung']='Khu Vực rửa bát';
$mod_c[$i]['bien']='rua_bat';
$mod_c[$i]['sql']='modc_rua_bat';
$mod_c[$i]['type']=0;
$i++;
$mod_c[$i]['noidung']='Các thang bộ thoát hiểm';
$mod_c[$i]['bien']='thang_bo';
$mod_c[$i]['sql']='modc_thang_bo';
$mod_c[$i]['type']=0;
$i++;
$mod_c[$i]['noidung']='Khu vực đỗ xe';
$mod_c[$i]['bien']='do_xe';
$mod_c[$i]['sql']='modc_do_xe';
$mod_c[$i]['type']=1;
$i++;
$mod_c[$i]['noidung']='Tình trạng vệ sinh';
$mod_c[$i]['bien']='ve_sinh_do_xe';
$mod_c[$i]['sql']='modc_ve_sinh_do_xe';
$mod_c[$i]['type']=0;
$i++;
$mod_c[$i]['noidung']='CBNV có mặt làm việc theo lịch';
$mod_c[$i]['bien']='cbnv_do_xe';
$mod_c[$i]['sql']='modc_cbnv_do_xe';
$mod_c[$i]['type']=0;
$i++;
$mod_c[$i]['noidung']='Khu vực giặt là';
$mod_c[$i]['bien']='giat_la';
$mod_c[$i]['sql']='modc_giat_la';
$mod_c[$i]['type']=1;
$i++;
$mod_c[$i]['noidung']='CBNV có mặt làm việc theo lịch';
$mod_c[$i]['bien']='cbnv_giat_la';
$mod_c[$i]['sql']='modc_cbnv_giat_la';
$mod_c[$i]['type']=0;
$i++;
$mod_c[$i]['noidung']='Tình trạng vệ sinh';
$mod_c[$i]['bien']='ve_sinh_giat_la';
$mod_c[$i]['sql']='modc_ve_sinh_giat_la';
$mod_c[$i]['type']=0;
$i++;
$mod_c[$i]['noidung']='Phòng đồng phục';
$mod_c[$i]['bien']='phong_dong_phuc';
$mod_c[$i]['sql']='modc_phong_dong_phuc';
$mod_c[$i]['type']=0;
$i++;
$mod_c[$i]['noidung']='Văn phòng Buồng';
$mod_c[$i]['bien']='van_phong_buong';
$mod_c[$i]['sql']='modc_van_phong_buong';
$mod_c[$i]['type']=0;
$i++;
$mod_c[$i]['noidung']='Khu vực Văn Phòng';
$mod_c[$i]['bien']='van_phong';
$mod_c[$i]['sql']='modc_van_phong';
$mod_c[$i]['type']=1;
$i++;
$mod_c[$i]['noidung']='Các cửa khóa, đèn tắt';
$mod_c[$i]['bien']='khoa_cua';
$mod_c[$i]['sql']='modc_khoa_cua';
$mod_c[$i]['type']=0;
$i++;
$mod_c[$i]['noidung']='Tình trạng vệ sinh';
$mod_c[$i]['bien']='ve_sinh_van_phong';
$mod_c[$i]['sql']='modc_ve_sinh_van_phong';
$mod_c[$i]['type']=0;
$i++;
$mod_c[$i]['noidung']='Khu vực Sảnh';
$mod_c[$i]['bien']='sanh';
$mod_c[$i]['sql']='modc_sanh';
$mod_c[$i]['type']=1;
$i++;
$mod_c[$i]['noidung']='Các biển hiệu';
$mod_c[$i]['bien']='bien_hieu';
$mod_c[$i]['sql']='modc_bien_hieu';
$mod_c[$i]['type']=0;
$i++;
$mod_c[$i]['noidung']='Nhạc nền';
$mod_c[$i]['bien']='nhac_nen_sanh';
$mod_c[$i]['sql']='modc_nhac_nen_sanh';
$mod_c[$i]['type']=0;
$i++;
$mod_c[$i]['noidung']='Đèn bật theo thời gian biểu';
$mod_c[$i]['bien']='den_sanh_bat';
$mod_c[$i]['sql']='modc_den_sanh_bat';
$mod_c[$i]['type']=0;
$i++;
$mod_c[$i]['noidung']='Diện mạo của CBNV';
$mod_c[$i]['bien']='sanh_dien_mao';
$mod_c[$i]['sql']='modc_sanh_dien_mao';
$mod_c[$i]['type']=0;
$i++;
$mod_c[$i]['noidung']='Tình trạng vệ sinh ở quầy Lễ tân';
$mod_c[$i]['bien']='ve_sinh_le_tan';
$mod_c[$i]['sql']='modc_ve_sinh_le_tan';
$mod_c[$i]['type']=0;
$i++;
$mod_c[$i]['noidung']='Tình trạng vệ sinh chung khu vực Sảnh';
$mod_c[$i]['bien']='ve_sinh_sanh';
$mod_c[$i]['sql']='modc_ve_sinh_sanh';
$mod_c[$i]['type']=0;
$i++;
$mod_c[$i]['noidung']='Nhà vệ sinh công cộng';
$mod_c[$i]['bien']='ve_sinh_chung';
$mod_c[$i]['sql']='modc_ve_sinh_chung';
$mod_c[$i]['type']=0;
$i++;
$mod_c[$i]['noidung']='Thang cuốn, thang bộ';
$mod_c[$i]['bien']='thang_may';
$mod_c[$i]['sql']='modc_thang_may';
$mod_c[$i]['type']=0;
$i++;
$mod_c[$i]['noidung']='CBNV có mặt làm việc theo lịch';
$mod_c[$i]['bien']='nhan_vien_le_tan';
$mod_c[$i]['sql']='modc_nhan_vien_le_tan';
$mod_c[$i]['type']=0;
$i++;
$mod_c[$i]['noidung']='Sự quan tâm đến khách hàng';
$mod_c[$i]['bien']='quan_tam_khach_hang';
$mod_c[$i]['sql']='modc_quan_tam_khach_hang';
$mod_c[$i]['type']=0;
$i++;
$mod_c[$i]['noidung']='Phòng chờ VIP';
$mod_c[$i]['bien']='phong_cho_vip';
$mod_c[$i]['sql']='modc_phong_cho_vip';
$mod_c[$i]['type']=0;
$i++;
$mod_c[$i]['noidung']='Văn phòng Lễ tân';
$mod_c[$i]['bien']='van_phong_le_tan';
$mod_c[$i]['sql']='modc_van_phong_le_tan';
$mod_c[$i]['type']=0;
$i++;
$mod_c[$i]['noidung']='Bar ở Sảnh';
$mod_c[$i]['bien']='bar_sanh';
$mod_c[$i]['sql']='modc_bar_sanh';
$mod_c[$i]['type']=1;
$i++;
$mod_c[$i]['noidung']='Số lượng khách';
$mod_c[$i]['bien']='bar_so_luong_khach';
$mod_c[$i]['sql']='modc_bar_so_luong_khach';
$mod_c[$i]['type']=0;
$i++;
$mod_c[$i]['noidung']='Nhạc nền';
$mod_c[$i]['bien']='bar_nhac_nen';
$mod_c[$i]['sql']='modc_bar_nhac_nen';
$mod_c[$i]['type']=0;
$i++;
$mod_c[$i]['noidung']='Đèn bật theo thời gian biểu';
$mod_c[$i]['bien']='bar_den_bat';
$mod_c[$i]['sql']='modc_bar_den_bat';
$mod_c[$i]['type']=0;
$i++;
$mod_c[$i]['noidung']='Diện mạo của CBNV';
$mod_c[$i]['bien']='bar_dien_mao';
$mod_c[$i]['sql']='modc_bar_dien_mao';
$mod_c[$i]['type']=0;
$i++;
$mod_c[$i]['noidung']='CBNV có mặt làm việc theo lịch';
$mod_c[$i]['bien']='bar_cbnv';
$mod_c[$i]['sql']='modc_bar_cbnv';
$mod_c[$i]['type']=0;
$i++;
$mod_c[$i]['noidung']='Tình trạng vệ sinh';
$mod_c[$i]['bien']='bar_ve_sinh';
$mod_c[$i]['sql']='modc_bar_ve_sinh';
$mod_c[$i]['type']=0;
$i++;
$mod_c[$i]['noidung']='Nhà hàng';
$mod_c[$i]['bien']='nha_hang';
$mod_c[$i]['sql']='modc_nha_hang';
$mod_c[$i]['type']=1;
$i++;
$mod_c[$i]['noidung']='Số lượng khách';
$mod_c[$i]['bien']='nh_so_khach';
$mod_c[$i]['sql']='modc_nh_so_khach';
$mod_c[$i]['type']=0;
$i++;
$mod_c[$i]['noidung']='Nhạc nền';
$mod_c[$i]['bien']='nh_nhac_nen';
$mod_c[$i]['sql']='modc_nh_nhac_nen';
$mod_c[$i]['type']=0;
$i++;
$mod_c[$i]['noidung']='Đèn bật theo thời gian biểu';
$mod_c[$i]['bien']='nh_den_bat';
$mod_c[$i]['sql']='modc_nh_den_bat';
$mod_c[$i]['type']=0;
$i++;
$mod_c[$i]['noidung']='Diện mạo của CBNV';
$mod_c[$i]['bien']='nh_dien_mao';
$mod_c[$i]['sql']='modc_nh_dien_mao';
$mod_c[$i]['type']=0;
$i++;
$mod_c[$i]['noidung']='CBNV có mặt làm việc theo lịch';
$mod_c[$i]['bien']='nh_nhan_vien';
$mod_c[$i]['sql']='modc_nh_nhan_vien';
$mod_c[$i]['type']=0;
$i++;
$mod_c[$i]['noidung']='Tình trạng thức ăn ở quầy tự chọn';
$mod_c[$i]['bien']='nh_thuc_an';
$mod_c[$i]['sql']='modc_nh_thuc_an';
$mod_c[$i]['type']=0;
$i++;
$mod_c[$i]['noidung']='Tình trạng vệ sinh của quầy tự chọn';
$mod_c[$i]['bien']='nh_ve_sinh';
$mod_c[$i]['sql']='modc_nh_ve_sinh';
$mod_c[$i]['type']=0;
$i++;
$mod_c[$i]['noidung']='Nhà vệ sinh công cộng';
$mod_c[$i]['bien']='nh_nha_ve_sinh';
$mod_c[$i]['sql']='modc_nh_nha_ve_sinh';
$mod_c[$i]['type']=0;
$i++;
$mod_c[$i]['noidung']='Khu vực chuẩn bị';
$mod_c[$i]['bien']='nh_chuan_bi';
$mod_c[$i]['sql']='modc_nh_chuan_bi';
$mod_c[$i]['type']=0;
$i++;
$mod_c[$i]['noidung']='Phòng hội nghị lớn';
$mod_c[$i]['bien']='phong_hoi_nghi';
$mod_c[$i]['sql']='modc_phong_hoi_nghi';
$mod_c[$i]['type']=1;
$i++;
$mod_c[$i]['noidung']='Chuẩn bị có sự kiện';
$mod_c[$i]['bien']='phn_co_su_kien';
$mod_c[$i]['sql']='modc_phn_co_su_kien';
$mod_c[$i]['type']=0;
$i++;
$mod_c[$i]['noidung']='Sự kiện, biển hiệu';
$mod_c[$i]['bien']='phn_bien_hieu';
$mod_c[$i]['sql']='modc_phn_bien_hieu';
$mod_c[$i]['type']=0;
$i++;
$mod_c[$i]['noidung']='Gặp gỡ chủ sự kiện';
$mod_c[$i]['bien']='phn_chu_su_kien';
$mod_c[$i]['sql']='modc_phn_chu_su_kien';
$mod_c[$i]['type']=0;
$i++;
$mod_c[$i]['noidung']='Nhạc nền';
$mod_c[$i]['bien']='phn_nhac_nen';
$mod_c[$i]['sql']='modc_phn_nhac_nen';
$mod_c[$i]['type']=0;
$i++;
$mod_c[$i]['noidung']='Đèn bật theo thời gian biểu';
$mod_c[$i]['bien']='phn_den_bat';
$mod_c[$i]['sql']='modc_phn_den_bat';
$mod_c[$i]['type']=0;
$i++;
$mod_c[$i]['noidung']='Diện mạo của CBNV';
$mod_c[$i]['bien']='phn_dien_mao';
$mod_c[$i]['sql']='modc_phn_dien_mao';
$mod_c[$i]['type']=0;
$i++;
$mod_c[$i]['noidung']='CBNV có mặt làm việc theo lịch';
$mod_c[$i]['bien']='phn_cbnv';
$mod_c[$i]['sql']='modc_phn_cbnv';
$mod_c[$i]['type']=0;
$i++;
$mod_c[$i]['noidung']='Phòng tiệc';
$mod_c[$i]['bien']='phong_tiec';
$mod_c[$i]['sql']='modc_phong_tiec';
$mod_c[$i]['type']=1;
$i++;
$mod_c[$i]['noidung']='Chuẩn bị có sự kiện';
$mod_c[$i]['bien']='pt_co_su_kien';
$mod_c[$i]['sql']='modc_pt_co_su_kien';
$mod_c[$i]['type']=0;
$i++;
$mod_c[$i]['noidung']='Sự kiện, biển hiệu';
$mod_c[$i]['bien']='pt_bien_hieu';
$mod_c[$i]['sql']='modc_pt_bien_hieu';
$mod_c[$i]['type']=0;
$i++;
$mod_c[$i]['noidung']='Gặp gỡ chủ tiệc';
$mod_c[$i]['bien']='pt_chu_su_kien';
$mod_c[$i]['sql']='modc_pt_chu_su_kien';
$mod_c[$i]['type']=0;
$i++;
$mod_c[$i]['noidung']='Nhạc nền';
$mod_c[$i]['bien']='pt_nhac_nen';
$mod_c[$i]['sql']='modc_pt_nhac_nen';
$mod_c[$i]['type']=0;
$i++;
$mod_c[$i]['noidung']='Đèn bật theo thời gian biểu';
$mod_c[$i]['bien']='pt_den_bat';
$mod_c[$i]['sql']='modc_pt_den_bat';
$mod_c[$i]['type']=0;
$i++;
$mod_c[$i]['noidung']='Diện mạo của CBNV';
$mod_c[$i]['bien']='pt_dien_mao';
$mod_c[$i]['sql']='modc_pt_dien_mao';
$mod_c[$i]['type']=0;
$i++;
$mod_c[$i]['noidung']='CBNV có mặt làm việc theo lịch';
$mod_c[$i]['bien']='pt_cbnv';
$mod_c[$i]['sql']='modc_pt_cbnv';
$mod_c[$i]['type']=0;
$i++;
$mod_c[$i]['noidung']='Khu vực mát xa';
$mod_c[$i]['bien']='massage';
$mod_c[$i]['sql']='modc_massage';
$mod_c[$i]['type']=1;
$i++;
$mod_c[$i]['noidung']='Số lượng khách';
$mod_c[$i]['bien']='mas_so_luong';
$mod_c[$i]['sql']='modc_mas_so_luong';
$mod_c[$i]['type']=0;
$i++;
$mod_c[$i]['noidung']='Diện mạo của CBNV';
$mod_c[$i]['bien']='mas_dien_mao';
$mod_c[$i]['sql']='modc_mas_dien_mao';
$mod_c[$i]['type']=0;
$i++;
$mod_c[$i]['noidung']='Tình trạng vệ sinh';
$mod_c[$i]['bien']='mas_ve_sinh';
$mod_c[$i]['sql']='modc_mas_ve_sinh';
$mod_c[$i]['type']=0;
$i++;
$mod_c[$i]['noidung']='Khu vực bể bơi, phòng tập';
$mod_c[$i]['bien']='be_boi';
$mod_c[$i]['sql']='modc_be_boi';
$mod_c[$i]['type']=1;
$i++;
$mod_c[$i]['noidung']='Số lượng khách';
$mod_c[$i]['bien']='bb_so_khach';
$mod_c[$i]['sql']='modc_bb_so_khach';
$mod_c[$i]['type']=0;
$i++;
$mod_c[$i]['noidung']='Nhạc nền';
$mod_c[$i]['bien']='bb_nhac_nen';
$mod_c[$i]['sql']='modc_bb_nhac_nen';
$mod_c[$i]['type']=0;
$i++;
$mod_c[$i]['noidung']='Bật đèn theo thời gian biểu';
$mod_c[$i]['bien']='bb_bat_den';
$mod_c[$i]['sql']='modc_bb_bat_den';
$mod_c[$i]['type']=0;
$i++;
$mod_c[$i]['noidung']='Diện mạo của CBNV';
$mod_c[$i]['bien']='bb_dien_mao';
$mod_c[$i]['sql']='modc_bb_dien_mao';
$mod_c[$i]['type']=0;
$i++;
$mod_c[$i]['noidung']='CBNV có mặt làm việc theo lịch';
$mod_c[$i]['bien']='bb_cbnv';
$mod_c[$i]['sql']='modc_bb_cbnv';
$mod_c[$i]['type']=0;
$i++;
$mod_c[$i]['noidung']='Bar và ghế bể bơi';
$mod_c[$i]['bien']='bb_ghe';
$mod_c[$i]['sql']='modc_bb_ghe';
$mod_c[$i]['type']=0;
$i++;
$mod_c[$i]['noidung']='Tình trạng vệ sinh khu vực thay đồ';
$mod_c[$i]['bien']='bb_ve_sinh_thay_do';
$mod_c[$i]['sql']='modc_bb_ve_sinh_thay_do';
$mod_c[$i]['type']=0;
$i++;
$mod_c[$i]['noidung']='Tình trạng vệ sinh khu tắm tráng';
$mod_c[$i]['bien']='bb_ve_sinh_tam';
$mod_c[$i]['sql']='modc_bb_ve_sinh_tam';
$mod_c[$i]['type']=0;
$i++;
$mod_c[$i]['noidung']='Gặp khách và ý kiến của khách';
$mod_c[$i]['bien']='y_kien';
$mod_c[$i]['sql']='modc_y_kien';
$mod_c[$i]['type']=2;
$mod_c[$i]['noidung2']='';
$i++;
$mod_c[$i]['noidung']='Đề xuất để cải thiện';
$mod_c[$i]['bien']='de_xuat';
$mod_c[$i]['sql']='modc_de_xuat';
$mod_c[$i]['type']=2;
$mod_c[$i]['noidung2']='';
$i++;
$mod_c[$i]['noidung']='Khách VIP đến và rời';
$mod_c[$i]['bien']='vip';
$mod_c[$i]['sql']='modc_vip';
$mod_c[$i]['type']=2;
$mod_c[$i]['noidung2']='';
?>