<?php 
$mucdich_arr=array();
$i=0;
$mucdich_arr[$i]['noidung']="Mục đích kỳ nghỉ của quý khách";
$mucdich_arr[]['giatri']=0;
$mucdich_arr[$i]['txt']=0;
$mucdich_arr[$i]['bien']='mucdich';
$mucdich_arr[$i]['sql']='ks18_muc_dich';
$mucdich_arr[$i]['bientxt']='mucdichtxt';
$mucdich_arr[$i]['sqltxt']='ks18_muc_dich_txt';
$i++;
$mucdich_arr[$i]['noidung']="Công tác";
$mucdich_arr[$i]['giatri']=1;
$mucdich_arr[$i]['txt']=0;
$i++;
$mucdich_arr[$i]['noidung']="Kết hợp";
$mucdich_arr[$i]['giatri']=2;
$mucdich_arr[$i]['txt']=0;
$i++;
$mucdich_arr[$i]['noidung']="Du lịch";
$mucdich_arr[$i]['giatri']=3;
$mucdich_arr[$i]['txt']=0;
$i++;
$mucdich_arr[$i]['noidung']="Khác(Xin ghi rõ lý do)";
$mucdich_arr[$i]['giatri']=4;
$mucdich_arr[$i]['txt']=1;
$lydo_arr=array();
$i=0;
$lydo_arr[$i]['noidung']='Lý do quý khách lựa chọn chúng tôi?';
$lydo_arr[$i]['giatri']=0;
$lydo_arr[$i]['txt']=0;
$lydo_arr[$i]['bien']='lydo';
$lydo_arr[$i]['sql']='ks18_ly_do';
$i++;
$lydo_arr[$i]['noidung']='Hài lòng vì kỳ nghỉ trước';
$lydo_arr[$i]['giatri']=1;
$lydo_arr[$i]['txt']=0;
$i++;
$lydo_arr[$i]['noidung']='Vị trí của khách sạn';
$lydo_arr[$i]['giatri']=2;
$lydo_arr[$i]['txt']=0;
$i++;
$lydo_arr[$i]['noidung']='Giá thành phù hợp';
$lydo_arr[$i]['giatri']=3;
$lydo_arr[$i]['txt']=0;
$i++;
$lydo_arr[$i]['noidung']='Được giới thiệu';
$lydo_arr[$i]['giatri']=4;
$lydo_arr[$i]['txt']=0;
$lydo_arr[$i]['noidung']='Do công ty/ Công ty du lịch chọn';
$lydo_arr[$i]['giatri']=5;
$lydo_arr[$i]['txt']=0;
$kenhdatphong_arr=array();
$i=0;
$kenhdatphong_arr[$i]['noidung']='Quý khách đặt phòng qua kênh nào?';
$kenhdatphong_arr[$i]['giatri']=0;
$kenhdatphong_arr[$i]['txt']=0;
$kenhdatphong_arr[$i]['bien']='kenhdatphong';
$kenhdatphong_arr[$i]['sql']='ks18_kenh_dat_phong';
$kenhdatphong_arr[$i]['bientxt']='kenhdatphongtxt';
$kenhdatphong_arr[$i]['sqltxt']='ks18_kenh_dat_phong_txt';
$i++;
$kenhdatphong_arr[$i]['noidung']='Trực tiếp tại khách sạn';
$kenhdatphong_arr[$i]['giatri']=1;
$kenhdatphong_arr[$i]['txt']=0;
$i++;
$kenhdatphong_arr[$i]['noidung']='Qua công ty du lịch';
$kenhdatphong_arr[$i]['giatri']=2;
$kenhdatphong_arr[$i]['txt']=0;
$i++;
$kenhdatphong_arr[$i]['noidung']='Công ty đặt';
$kenhdatphong_arr[$i]['giatri']=3;
$kenhdatphong_arr[$i]['txt']=0;
$i++;
$kenhdatphong_arr[$i]['noidung']='Qua website của khách sạn';
$kenhdatphong_arr[$i]['giatri']=4;
$kenhdatphong_arr[$i]['txt']=0;
$i++;
$kenhdatphong_arr[$i]['noidung']='Qua website khác(Xin ghi tên website)';
$kenhdatphong_arr[$i]['giatri']=5;
$kenhdatphong_arr[$i]['txt']=1;
$danhgia_arr=array();
$danhgia_arr['danhgia']['noidung']='Xin quý khách vui lòng đánh giá mức độ hài lòng của mình tại khách sạn chúng tôi';
$danhgia_arr['danhgiachung']['noidung']='Đánh giá chung về kỳ nghỉ';
$danhgia_arr['danhgiachung']['bien']='danhgiachung';
$danhgia_arr['danhgiachung']['sql']='ks18_danh_gia_chung';
$danhgia_arr['datphong']['noidung']='Đặt phòng';
$danhgia_arr['datphong']['bien']='datphong';
$danhgia_arr['datphong']['sql']='ks18_dat_phong';
$danhgia_arr['checkin']['noidung']='Quá trình check-in';
$danhgia_arr['checkin']['bien']='checkin';
$danhgia_arr['checkin']['sql']='ks18_checkin';
$danhgia_arr['checkout']['noidung']='Quá trình check-out';
$danhgia_arr['checkout']['bien']='checkout';
$danhgia_arr['checkout']['sql']='ks18_checkout';
$danhgia_arr['dichvuhanhly']['noidung']='Dịch vụ hành lý & quầy thông tin';
$danhgia_arr['dichvuhanhly']['bien']='dichvuhanhly';
$danhgia_arr['dichvuhanhly']['sql']='ks18_dich_vu_hanh_ly';
$danhgia_arr['vesinh']['noidung']='Vệ sinh trong phòng';
$danhgia_arr['vesinh']['bien']='vesinh';
$danhgia_arr['vesinh']['sql']='ks18_ve_sinh';
$danhgia_arr['tiennghi']['noidung']='Tiện nghi trong phòng';
$danhgia_arr['tiennghi']['bien']='tiennghi';
$danhgia_arr['tiennghi']['sql']='ks18_tien_nghi';
$danhgia_arr['ansang']['noidung']='Chất lượng đồ ăn sáng';
$danhgia_arr['ansang']['bien']='ansang';
$danhgia_arr['ansang']['sql']='ks18_an_sang';
$danhgia_arr['thaido']['noidung']='Thái độ của nhân viên';
$danhgia_arr['thaido']['bien']='thaido';
$danhgia_arr['thaido']['sql']='ks18_thai_do';
$vande_arr=array();
$vande_arr['chung']['noidung']='Quý khách vui lòng đánh dấu vào những vấn đề/ sự cố mà quý khách gặp phải trong kỳ nghỉ vừa qua(Nếu có)';
$vande_arr['vandedatphong']['noidung']='Đặt phòng';
$vande_arr['vandedatphong']['bien']='vandedatphong';
$vande_arr['vandedatphong']['sql']='ks18_van_de_dat_phong';
$vande_arr['vandecheckin']['noidung']='Nhận phòng - Check in';
$vande_arr['vandecheckin']['bien']='vandecheckin';
$vande_arr['vandecheckin']['sql']='ks18_van_de_checkin';
$vande_arr['vandecheckout']['noidung']='Trả phòng - Check out';
$vande_arr['vandecheckout']['bien']='vandecheckout';
$vande_arr['vandecheckout']['sql']='ks18_van_de_checkout';
$vande_arr['vandevesinh']['noidung']='Vệ sinh phòng khách';
$vande_arr['vandevesinh']['bien']='vandevesinh';
$vande_arr['vandevesinh']['sql']='ks18_van_de_ve_sinh';
$vande_arr['cooling']['noidung']='Hệ thống điều hòa';
$vande_arr['cooling']['bien']='cooling';
$vande_arr['cooling']['sql']='ks18_cooling';
$vande_arr['internet']['noidung']='Mạng Internet';
$vande_arr['internet']['bien']='internet';
$vande_arr['internet']['sql']='ks18_internet';
$vande_arr['amthuc']['noidung']='Dịch vụ ẩm thực';
$vande_arr['amthuc']['bien']='amthuc';
$vande_arr['amthuc']['sql']='ks18_am_thuc';
$vande_arr['hoadon']['noidung']='Hóa đơn thanh toán';
$vande_arr['hoadon']['bien']='hoadon';
$vande_arr['hoadon']['sql']='ks18_hoa_don';
$vande_arr['nhanvien']['noidung']='Nhân viên';
$vande_arr['nhanvien']['bien']='nhanvien';
$vande_arr['nhanvien']['sql']='ks18_nhan_vien';
$vande_arr['vandekhac']['noidung']='Vấn đề khác';
$vande_arr['vandekhac']['bien']='vandekhac';
$vande_arr['vandekhac']['bientxt']='vandekhac_txt';
$vande_arr['vandekhac']['sql']='ks18_van_de_khac';
$vande_arr['vandekhac']['sqltxt']='ks18_van_de_khac_txt';
$vande_arr['cachgiaiquyet']['noidung']='Quý khách có hài lòng với cách giải quyết vấn đề/ sự cố không?';
$vande_arr['cachgiaiquyet']['bien']='cachgiaiquyet';
$vande_arr['cachgiaiquyet']['sql']='ks18_cach_giai_quyet';
$vande_arr['nhanxet']['noidung']='Nhận xét của quý khách';
$vande_arr['nhanxet']['bien']='nhanxet';
$vande_arr['nhanxet']['sql']='ks18_nhan_xet';

?>