<?php
		if(isset($sophieu)) soPhieu('sophieu',$sophieu); else soPhieu('sophieu');
		if(isset($ngay_khao_sat)) ngayKhaoSat('ngay_khao_sat',$ngay_khao_sat); else ngayKhaoSat('ngay_khao_sat');
		tieuDe('Đăng ký nhận phòng');
			if(isset($checkin_tiep_don)) chon('Vui lòng đánh giá phong cách tiếp đón','checkin_tiep_don',$checkin_tiep_don); else chon('Vui lòng đánh giá phong cách tiếp đón','checkin_tiep_don'); 
			if(isset($checkin_dang_ky)) chonYesNo('Đăng ký nhận phòng nhanh gọn không?','checkin_dang_ky',$checkin_dang_ky); else chonYesNo('Đăng ký nhận phòng nhanh gọn không?','checkin_dang_ky');
			if(isset($checkin_yeu_cau))chonYesNo('Đặt phòng có theo yêu cầu của quý khách không?','checkin_yeu_cau',$checkin_yeu_cau); else chonYesNo('Đặt phòng có theo yêu cầu của quý khách không?','checkin_yeu_cau');
			if(isset($checkin_chao_don)) chonYesNo('Quý khách có được chào đón niềm nở không?','checkin_chao_don',$checkin_chao_don); else chonYesNo('Quý khách có được chào đón niềm nở không?','checkin_chao_don');
		tieuDe('chất lượng phòng nghỉ');
			if(isset($room_chung)) chon('Vui lòng đánh giá chung về chất lượng phòng nghỉ','room_chung',$room_chung); else chon('Vui lòng đánh giá chung về chất lượng phòng nghỉ','room_chung'); 
			if(isset($room_thoai_mai))  chon('Mức độ thoải mái','room_thoai_mai',$room_thoai_mai); else chon('Mức độ thoải mái','room_thoai_mai');
			if(isset($room_sach_se)) chon('Mức độ sạch sẽ trong phòng','room_sach_se',$room_sach_se); else chon('Mức độ sạch sẽ trong phòng','room_sach_se');
			if(isset($room_an_toan)) chon('Mức độ an toàn','room_an_toan',$room_an_toan); else chon('Mức độ an toàn','room_an_toan');
			if(isset($room_anh_sang)) chonYesNo('Hệ thống ánh sáng đảm bảo để làm việc không? ','room_anh_sang',$room_anh_sang); else chonYesNo('Hệ thống ánh sáng đảm bảo để làm việc không? ','room_anh_sang');
			if(isset($room_internet)) chonYesNo('Internet nhanh và dễ truy cập không? ','room_internet',$room_internet); else chonYesNo('Internet nhanh và dễ truy cập không? ','room_internet');
			if(isset($room_tot_hon)) dongTxt('Bằng cách nào chúng tôi có thể làm cho Quý khách thoải mái và dễ chịu hơn trong phòng nghỉ?','room_tot_hon',$room_tot_hon); else dongTxt('Bằng cách nào chúng tôi có thể làm cho Quý khách thoải mái và dễ chịu hơn trong phòng nghỉ?','room_tot_hon');
		tieuDe('Trang thiết bị khách sạn');	
			if(isset($fac_chung)) chon('Vui lòng đánh giá trải nghiệm chung về trang thiết bị khách sạn trong suốt thời gian nghỉ lại đây','fac_chung',$fac_chung); else chon('Vui lòng đánh giá trải nghiệm chung về trang thiết bị khách sạn trong suốt thời gian nghỉ lại đây','fac_chung');
			tieuDe2('Trung tâm thể dục thể thao');
				if(isset($fac_fit_dich_vu)) chon('Dịch vụ','fac_fit_dich_vu',$fac_fit_dich_vu); else chon('Dịch vụ','fac_fit_dich_vu');
				if(isset($fac_fit_ky_nang))chon('Kỹ năng và kiến thức','fac_fit_ky_nang',$fac_fit_ky_nang); else chon('Kỹ năng và kiến thức','fac_fit_ky_nang');
				if(isset($fac_fit_trang_bi)) chon('Trang thiết bị','fac_fit_trang_bi',$fac_fit_trang_bi); else chon('Trang thiết bị','fac_fit_trang_bi'); 
			tieuDe2('Spa & Massage');
				if(isset($fac_spa_dich_vu)) chon('Dịch vụ','fac_spa_dich_vu',$fac_spa_dich_vu); else chon('Dịch vụ','fac_spa_dich_vu');
				if(isset($fac_spa_ky_nang)) chon('Kỹ năng và kiến thức','fac_spa_ky_nang',$fac_spa_ky_nang); else chon('Kỹ năng và kiến thức','fac_spa_ky_nang');
				if(isset($fac_spa_trang_bi)) chon('Trang thiết bị','fac_spa_trang_bi',$fac_spa_trang_bi); else chon('Trang thiết bị','fac_spa_trang_bi');
			tieuDe2('Bể bơi');
				if(isset($fac_swim_dich_vu)) chon('Dịch vụ','fac_swim_dich_vu',$fac_swim_dich_vu); else chon('Dịch vụ','fac_swim_dich_vu');
				if(isset($fac_swim_ky_nang)) chon('Kỹ năng và kiến thức','fac_swim_ky_nang',$fac_swim_ky_nang); else chon('Kỹ năng và kiến thức','fac_swim_ky_nang');
				if(isset($fac_swim_trang_bi)) chon('Trang thiết bị','fac_swim_trang_bi',$fac_swim_trang_bi); else chon('Trang thiết bị','fac_swim_trang_bi');
			tieuDe2('Dịch vụ văn phòng');
				if(isset($fac_busi_dich_vu)) chon('Dịch vụ','fac_busi_dich_vu',$fac_busi_dich_vu); else chon('Dịch vụ','fac_busi_dich_vu');
				if(isset($fac_busi_ky_nang)) chon('Kỹ năng và kiến thức','fac_busi_ky_nang',$fac_busi_ky_nang); else chon('Kỹ năng và kiến thức','fac_busi_ky_nang');
				if(isset($fac_busi_trang_bi)) chon('Trang thiết bị','fac_busi_trang_bi',$fac_busi_trang_bi); else chon('Trang thiết bị','fac_busi_trang_bi'); 
		tieuDe('nhà hàng và bar');	
			if(isset($rest_chung)) chon('Vui lòng đánh giá trải nghiệm chung về khu vực nhà hàng và bar','rest_chung',$rest_chung); else chon('Vui lòng đánh giá trải nghiệm chung về khu vực nhà hàng và bar','rest_chung');
			tieuDe2('Nhà hàng');
				if(isset($rest_dich_vu)) chon('Chất lượng dịch vụ','rest_dich_vu',$rest_dich_vu); else chon('Chất lượng dịch vụ','rest_dich_vu');
				if(isset($rest_do_an)) chon('Chất lượng đồ ăn','rest_do_an',$rest_do_an); else chon('Chất lượng đồ ăn','rest_do_an');
				if(isset($rest_do_uong)) chon('Chất lượng đồ uống','rest_do_uong',$rest_do_uong); else chon('Chất lượng đồ uống','rest_do_uong');
				if(isset($rest_trang_tri)) chon('Trang trí và không gian','rest_trang_tri',$rest_trang_tri); else chon('Trang trí và không gian','rest_trang_tri');
		tieuDe('Quý khách vui lòng góp ý thêm để chúng tôi cải tiến chất lượng dịch vụ?');
			if(isset($how_an_uong)) dongTxt('Chất lượng thức ăn và đồ uống','how_an_uong',$how_an_uong); else dongTxt('Chất lượng thức ăn và đồ uống','how_an_uong');
			if(isset($how_dich_vu)) dongTxt('Dịch vụ khách sạn','how_dich_vu',$how_dich_vu); else dongTxt('Dịch vụ khách sạn','how_dich_vu');
			if(isset($how_trang_bi)) dongTxt('Trang thiết bị khách sạn','how_trang_bi',$how_trang_bi); else dongTxt('Trang thiết bị khách sạn','how_trang_bi');
			if(isset($how_trang_tri)) dongTxt('Trang trí','how_trang_tri',$how_trang_tri); else dongTxt('Trang trí','how_trang_tri');
			if(isset($how_khac)) dongTxt('Khác','how_khac',$how_khac); else dongTxt('Khác','how_khac');
		tieuDe('Nhân viên khách sạn');
			if(isset($employ_chung)) chon('Vui lòng đánh giá về nhân viên khách sạn','employ_chung',$employ_chung); else chon('Vui lòng đánh giá về nhân viên khách sạn','employ_chung');
			tieuDe2('Khi nhân viên hỗ trợ Quý khách, họ có: ');
				if(isset($employ_tu_tin)) chonYesNo('Thể hiện thái độ tự tin khi thực hiện yêu cầu của quý khách?','employ_tu_tin',$employ_tu_tin); else chonYesNo('Thể hiện thái độ tự tin khi thực hiện yêu cầu của quý khách?','employ_tu_tin');
				if(isset($employ_nhanh)) chonYesNo('Thực hiện nhanh và hiệu quả yêu cầu của quý khách?','employ_nhanh',$employ_nhanh); else chonYesNo('Thực hiện nhanh và hiệu quả yêu cầu của quý khách?','employ_nhanh');
				if(isset($employ_chuyen_nghiep)) chonYesNo('Thể hiện thái độ tận tâm và chuyên nghiệp','employ_chuyen_nghiep',$employ_chuyen_nghiep); else chonYesNo('Thể hiện thái độ tận tâm và chuyên nghiệp','employ_chuyen_nghiep');
				if(isset($employ_hai_long)) chonYesNo('Hoàn toàn làm hài lòng quý khách?','employ_hai_long',$employ_hai_long); else chonYesNo('Hoàn toàn làm hài lòng quý khách?','employ_hai_long');
				if(isset($employ_mong_doi)) chonYesNo('Có nhân viên nào thực hiện vượt sự mong đợi của Quý khách không?','employ_mong_doi',$employ_mong_doi); else chonYesNo('Có nhân viên nào thực hiện vượt sự mong đợi của Quý khách không?','employ_mong_doi');
				if(isset($employ_ten_nhan_vien)) dongTxt('Vui lòng cho biết tên nhân viên:','employ_ten_nhan_vien',$employ_ten_nhan_vien); else dongTxt('Vui lòng cho biết tên nhân viên:','employ_ten_nhan_vien');
		tieuDe('Đánh giá mức độ hài lòng chung');
			if(isset($overall_how)) dongTxt('Chúng tôi nên làm gì để nâng cao chất lượng dịch vụ nhằm đáp ứng tốt nhất nhu cầu của quý khách?','overall_how',$overall_how); else dongTxt('Chúng tôi nên làm gì để nâng cao chất lượng dịch vụ nhằm đáp ứng tốt nhất nhu cầu của quý khách?','overall_how');
			if(isset($overall_chung)) chon('Vui lòng đánh giá chung về khách sạn','overall_chung',$overall_chung); else chon('Vui lòng đánh giá chung về khách sạn','overall_chung');
		tieuDe('Đánh giá mức độ hài lòng chung');
			if(isset($overall_ho_ten)) dongTxt('Họ và tên:','overall_ho_ten',$overall_ho_ten); else dongTxt('Họ và tên:','overall_ho_ten');
			if(isset($overall_email)) dongTxt('Email:','overall_email',$overall_email); else dongTxt('Email:','overall_email');
			if(isset($overall_dien_thoai)) dongTxt('Số điện thoại:','overall_dien_thoai',$overall_dien_thoai); else dongTxt('Số điện thoại:','overall_dien_thoai');
			if(isset($overall_so_phong)) dongTxt('Số phòng:','overall_so_phong',$overall_so_phong); else dongTxt('Số phòng:','overall_so_phong');
			if(isset($overall_thoi_gian)) dongTxt('Thời gian lưu trú:','overall_thoi_gian',$overall_thoi_gian); else dongTxt('Thời gian lưu trú:','overall_thoi_gian');
			if(isset($overall_cong_ty)) dongTxt('Công ty:','overall_cong_ty',$overall_cong_ty); else dongTxt('Công ty:','overall_cong_ty');
?>